added requirements for portaudio for spotify

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -1251,6 +1251,12 @@ case "${1}" in
                 echo -e "$basename0: internal error - portaudio is required to be installed ..."; 
              fi
              exit 1
+             find /usr/include -name "portaudio.h" |xargs grep -v "port" &> /dev/null
+               if [[ $? -ne 0 ]]; then 
+                    echo -e "$basename$0: internal error -- portaudio is requrired to be installed"
+                    exit 1
+               fi
+
              find /usr/include -type d |grep 'libspotify' &> /dev/null
              if [[ "$?" -ne "0" ]]; then
              if [[ -z "$LIBSPOTIFY" ]]; then
