added google instead of 1.1.1.1 for check connection

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -114,7 +114,7 @@ emagnet_required_stuff(){ if ! [[ -d "$HOME/.config/emagnet/" ]]; then mkdir -p 
 emagnet_conf(){ CONF="$HOME/.config/emagnet/emagnet.conf";. "$CONF" ;}
 emagnet_mustberoot(){(( ${EUID} > 0 )) && printf "%s\n" "$basename$0: internal error -- root privileges is required" && exit 1;  }
 emagnet_clear(){ clear;}
-emagnet_iconnection(){ ping -i "1" -c 1 1.1.1.1 &> /dev/null;if [[ "$?" -gt "0" ]];then echo -e "$basename$0: internal error -- no internet connection, can't connect to pastebin"; exit 1;fi; }
+emagnet_iconnection(){ ping -i "1" -c 1 google.com &> /dev/null;if [[ "$?" -gt "0" ]];then echo -e "$basename$0: internal error -- no internet connection, can't connect to pastebin"; exit 1;fi; }
 emagnet_license(){ printf "%s\n" "Printing LICENSE - Use 'q' to quit";sleep 2;curl -s "https://nr1.nu/licenses/LICENSE.md"|less;printf "%s\n" "Thank you.." ;}
 emagnet_is_this_android(){ getprop &> /dev/null; [[ "$?" -eq "0" ]] && sed -i '204d' "$CONF"; sed -i '204 i ANDROID=true' "$CONF";}
 emagnet_not_available_on_android(){ echo "This feature is not supported on your $(getprop ro.model.name)" device;exit 1;}
@@ -1027,15 +1027,15 @@ emagnet_search() {
     emagnet_banner
     echo -e "           * * * * *  EMAGNET SEARCH MENU  * * * * * \n"
     echo -e "=================================================================\n"
-    echo -e " [0] - Email Addresses"
-    echo -e " [1] - Email Addresses incl. Passwords"
-    echo -e " [2] - Amex, Master Card and Visa credit cards"
-    echo -e " [3] - IPv4 Addresses"
-    echo -e " [4] - IPv6 Addresses"
-    echo -e " [5] - Search files that contains PayPal, Neteller or Skrill words"
-    echo -e " [6] - Find urls that is for live/online streaming"
-    echo -e " [7] - Find hidden onion urls that being shared"
-    echo -e " [8] - Custom Search for anything you wanna find"
+    echo -e " [1] - Email Addresses"
+    echo -e " [2] - Email Addresses incl. Passwords"
+    echo -e " [3] - Amex, Master Card and Visa credit cards"
+    echo -e " [4] - IPv4 Addresses"
+    echo -e " [5] - IPv6 Addresses"
+    echo -e " [6] - Search files that contains PayPal, Neteller or Skrill words"
+    echo -e " [7] - Find urls that is for live/online streaming"
+    echo -e " [8] - Find hidden onion urls that being shared"
+    echo -e " [9] - Custom Search for anything you wanna find"
     echo -e " [q] - Quit\n"
     echo -e "=================================================================\n"
 
@@ -1068,11 +1068,11 @@ emagnet_findcreditcards() {
 }
 
 emagnet_findipv4addresses() {
-     grep -roE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' $EMAGNET|awk -F":" '{print $2}'|awk -F, '!seen[$1]++'|awk '{print NR-1 "-> " $0}'
+     grep -roE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' $EMAGNET|awk -F":" '{print $2}'|awk '{print NR-1 "-> " $0}'
 }
 
 emagnet_findipv6addresses() {
-    grep -roE "\b([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}\b" $EMAGNET|awk -F, '!seen[$1]++'|awk '{print NR-1 "-> " $0}'|cut -d: -f2-
+    grep -roE "\b([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}\b" $EMAGNET|awk '{print NR-1 "-> " $0}'|cut -d: -f2-
 }
 
 emagnet_findpaypalleaks() {
@@ -1084,7 +1084,7 @@ emagnet_findstreaming() {
 }
 
 emagnet_findonionurls() {
-     grep -rEo "h....\/\/.*onion$" $EMAGNET|awk -F':' '{print $2}'|awk -F, '!seen[$1]++'|awk '{print NR-1 "-> " $0}'
+     grep -rEo "h....\/\/.*onion$" $EMAGNET|awk -F':' '{print $2}'|awk '{print NR-1 "-> " $0}'
 }
 
 emagnet_customsearch() {
@@ -1098,10 +1098,11 @@ read -p " [O] - Option: " diagst
                 2) emagnet_findemailsandpasswords                                                   ;;
                 3) emagnet_findcreditcards                                                          ;;
                 4) emagnet_findipv4addresses                                                        ;;
-                5) emagnet_findpaypalleaks                                                          ;;
-                6) emagnet_findstreaming                                                            ;;
-                7) emagnet_findonionurls                                                            ;;
-                8) emagnet_customsearch                                                             ;;
+                5) emagnet_findipv6addresses                                                        ;;
+                6) emagnet_findpaypalleaks                                                          ;;
+                7) emagnet_findstreaming                                                            ;;
+                8) emagnet_findonionurls                                                            ;;
+                9) emagnet_customsearch                                                             ;;
                 9) exit 0                                                                           ;;
                 *) echo -e "$basename$0: internal error -- $diagst is an unknown option, exiting.." ;;
                \?) echo -e "$basename$0: internal error -- $diagst is an Unknown option, exiting.." ;;
