fixed varibles

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -109,68 +109,19 @@ Usage: ./$basename$0 [--author] [--emagnet] [--option] .....
 EOF
 }
 
-emagnet_required_stuff() { 
-  if ! [[ -d "$HOME/.config/emagnet/" ]]; then 
-    mkdir -p "$HOME/.config/emagnet/tmp"
-  fi
-    cp "./emagnet.conf" $HOME/.config/emagnet/
-}
-
-emagnet_conf() { 
-  CONF="$HOME/.config/emagnet/emagnet.conf"
-  . "$CONF" 
-}
-
-emagnet_mustberoot() { 
-  (( ${EUID} > 0 )) && printf "%s\n" "$basename$0: internal error -- root privileges is required" && exit 1  
-}
-
-emagnet_clear(){ 
-  clear
-}
-
-emagnet_iconnection() { 
-  ping -i "1" -c 1 google.com &> /dev/null
-     if [[ "$?" -gt "0" ]]; then 
-      echo -e "$basename$0: internal error -- no internet connection, can't connect to pastebin"
-      exit 1
-     fi
-}
-
-emagnet_license() { 
-   printf "%s\n" "Printing LICENSE - Use 'q' to quit"
-   sleep 2
-   curl -s "https://nr1.nu/licenses/LICENSE.md"|less
-   printf "%s\n" "Thank you.." 
- }
-
-
-emagnet_requirements(){ 
-  for cmd in wget curl; do 
-   hash $cmd
-   if [[ "$?" -gt 0 ]]; then 
-    echo "$cmd is required to be installed, exiting."
-    exit 1
-    fi
-  done
- }
-
-emagnet_optional(){ 
-  sleep 0
-}
-
-emagnet_blocked(){ 
-   if ! [[ -s "$HOME/.config/emagnet/tmp/.emagnet" ]]; then 
-   curl -h "$HEADER"-Ls "$PASTEBIN" -H "$USERAGENT" > $HOME/.config/emagnet/tmp/.emagnet
-   fi
-}
-
-emagnet_paths(){ 
-  PATHS="${EMAGNETHOME} ${EMAGNETCRACKED} ${EMAGNETDB} ${EMAGNETPW} ${EMAGNETTEMP} ${EMAGNETCRAP} ${EMAGNETALL} ${EMAGNETARCHIVE} ${EMAGNETLOGS}"
-  for DIRS in ${PATHS}; do 
-    ! [[ -d "${DIRS}" ]] && mkdir -p "${DIRS}" &> /dev/null; done 
-}
-
+emagnet_required_stuff(){ if ! [[ -d "$HOME/.config/emagnet/" ]]; then mkdir -p "$HOME/.config/emagnet/tmp";fi;cp "./emagnet.conf" $HOME/.config/emagnet/;}
+emagnet_conf(){ CONF="$HOME/.config/emagnet/emagnet.conf";. "$CONF" ;}
+emagnet_mustberoot(){(( ${EUID} > 0 )) && printf "%s\n" "$basename$0: internal error -- root privileges is required" && exit 1;  }
+emagnet_clear(){ clear;}
+emagnet_iconnection(){ ping -i "1" -c 1 google.com &> /dev/null;if [[ "$?" -gt "0" ]];then echo -e "$basename$0: internal error -- no internet connection, can't connect to pastebin"; exit 1;fi; }
+emagnet_license(){ printf "%s\n" "Printing LICENSE - Use 'q' to quit";sleep 2;curl -s "https://nr1.nu/licenses/LICENSE.md"|less;printf "%s\n" "Thank you.." ;}
+emagnet_is_this_android(){ getprop &> /dev/null; [[ "$?" -eq "0" ]] && sed -i '204d' "$CONF"; sed -i '204 i ANDROID=true' "$CONF";}
+emagnet_not_available_on_android(){ echo "This feature is not supported on your $(getprop ro.model.name)" device;exit 1;}
+emagnet_requirements_android(){ for android_tools in curl wget; do hash "${android_tools}";done;[[ "$?" -ne "0" ]] && echo "You must install ${android_tools} on your device";exit 1;}
+emagnet_requirements(){ for cmd in wget curl; do hash $cmd; if [[ "$?" -gt 0 ]]; then echo "$cmd is required to be installed, exiting."; exit 1;fi;done;}
+emagnet_optional(){ sleep 0;}
+emagnet_blocked(){ if ! [[ -s "$HOME/.config/emagnet/tmp/.emagnet" ]]; then curl -h "$HEADER"-Ls "$PASTEBIN" -H "$USERAGENT" > $HOME/.config/emagnet/tmp/.emagnet;fi;} # 2FIX - Do we need this?
+emagnet_paths(){ PATHS="${EMAGNETHOME} ${EMAGNETCRACKED} ${EMAGNETDB} ${EMAGNETPW} ${EMAGNETTEMP} ${EMAGNETCRAP} ${EMAGNETALL} ${EMAGNETARCHIVE} ${EMAGNETLOGS}";for DIRS in ${PATHS}; do ! [[ -d "${DIRS}" ]] && mkdir -p "${DIRS}" &> /dev/null; done ;}
 CONF="$HOME/.config/emagnet/emagnet.conf"
 
 emagnet_mustbefilled() {
