better support for requirements

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -78,6 +78,7 @@ cat << EOF
 Usage: ./$basename$0 [--author] [--emagnet] [--option] .....
 
   -a, --author        Show author information
+  -A, --api           If you have a PRO account, set this to true
   -b, --backup        Create a compressed archive
                       - Available options: all/archive/incoming
   -B, --blocked       Check if your current IP has been blocked
@@ -110,6 +111,7 @@ Usage: ./$basename$0 [--author] [--emagnet] [--option] .....
 EOF
 }
 
+CONF="$HOME/.config/emagnet/emagnet.conf"
 emagnet_required_stuff(){ if ! [[ -d "$HOME/.config/emagnet/" ]]; then mkdir -p "$HOME/.config/emagnet/tmp";fi;cp "./emagnet.conf" $HOME/.config/emagnet/;}
 emagnet_conf(){ CONF="$HOME/.config/emagnet/emagnet.conf";. "$CONF" ;}
 emagnet_mustberoot(){(( ${EUID} > 0 )) && printf "%s\n" "$basename$0: internal error -- root privileges is required" && exit 1;  }
@@ -118,13 +120,22 @@ emagnet_iconnection(){ ping -i "1" -c 1 google.com &> /dev/null;if [[ "$?" -gt "
 emagnet_license(){ printf "%s\n" "Printing LICENSE - Use 'q' to quit";sleep 2;
 if [[ $PROXY = "true" ]]; then CURL="curl -x socks5h://$PROXYHOST:$PROXYPORT ";else CURL="curl -s ";fi;$CURL "https://nr1.nu/licenses/LICENSE.md"|less;printf "%s\n" "Thank you.." ;}
 emagnet_requirements(){
-for cmd in wget curl; do which $cmd &> /dev/null;if [[ "$?" -gt 0 ]]; then echo "$cmd is required to be installed, exiting."; exit 1;fi
+for cmd in wget curl; do which $cmd &> /dev/null;if [[ "$?" -gt 0 ]]; then echo -e "$basename$0: internal error -- $cmd is required to be installed, exiting."; exit 1;fi
 done;}
 emagnet_optional(){ sleep 0;}
 emagnet_blocked(){ if ! [[ -s "$HOME/.config/emagnet/tmp/.emagnet" ]]; then curl -h "$HEADER"-Ls "$PASTEBIN" -H "$USERAGENT" > $HOME/.config/emagnet/tmp/.emagnet;fi;} # 2FIX - Do we need this?
 emagnet_paths(){ PATHS="${EMAGNETHOME} ${EMAGNETCRACKED} ${EMAGNETDB} ${EMAGNETPW} ${EMAGNETTEMP} ${EMAGNETCRAP} ${EMAGNETALL} ${EMAGNETARCHIVE} ${EMAGNETLOGS}";for DIRS in ${PATHS}; do ! [[ -d "${DIRS}" ]] && mkdir -p "${DIRS}" &> /dev/null; done ;}
-CONF="$HOME/.config/emagnet/emagnet.conf"
 
+emagnet_firstrun() {
+        emagnet_requirements
+        if [[ ! -f $CONF ]]; then
+        emagnet_banner
+        printf "Do you have a PRO membership on pastebin.com and also\n"; read -p "did you whitlist your ip for scraping (yes/NO): " scraping
+          if [[ "$scraping" = "yes" ]]; then
+             sed -i 's/API=false/API=true/g' "$PWD/emagnet.conf"
+          fi
+    fi
+}
 emagnet_mustbefilled() {
   if [[ -z "$DEBUG"          ]];then sed -i "12d"  "$CONF";sed -i '12  i DEBUG=false'                                                                                                             "$CONF";fi
   if [[ -z "$PASTEBIN"       ]];then sed -i '21d'  "$CONF";sed -i '21  i PASTEBIN=https:\/\/www.pastebin.com'                                                                                     "$CONF";fi
@@ -910,27 +921,43 @@ emagnet_main() {
     else
       CURL="curl -s "
     fi
-    $CURL -H "$USERAGENT" -Ls "$PASTEBIN/archive" \
-   |awk -F'href="/' '{print $2}' \
-   |cut -d'"' -f1 \
-   |awk 'length($0)>6 && length($0)<9' \
-   |grep -v 'archive\|contact\|settings\|messages\|signup\|index.html' \
-   |awk '{print tolower($0)}' > $HOME/.config/emagnet/tmp/.emagnet1
-    ls -1 "$EMAGNETALL" \
-   |sort > "$HOME/.config/emagnet/tmp/.1"
-    cat "$HOME/.config/emagnet/tmp/.emagnet1" \
-   |sort \
-   |cut -d/ -f5 > "$HOME/.config/emagnet/tmp/.2"
-    grep  -v -x -F -f "$HOME/.config/emagnet/tmp/.1" "$HOME/.config/emagnet/tmp/.2" |awk -F, '!seen[$1]++' \
-   |sed "s/^/https:\/\/pastebin.com\/raw\//g" > "$HOME/.config/emagnet/tmp/.emagnet"
-    rm "$HOME/.config/emagnet/tmp/.1" "$HOME/.config/emagnet/tmp/.2" &> /dev/null
+    if ! [[ "$API" = "false" ]]; then
+        rm /root/.config/emagnet/tmp/.1 /root/.config/emagnet/tmp/.* &> /dev/null
+        curl -s https://scrape.pastebin.com/api_scraping.php|grep -Eo "(http|https)://[a-zA-Z0-9./?=_-]*"|awk 'length < 30' > $HOME/.config/emagnet/tmp/.emagnet1
+        ls -1 $EMAGNETALL|sort > "$HOME/.config/emagnet/tmp/.1"
+        cat "$HOME/.config/emagnet/tmp/.emagnet1"|sort|cut -d/ -f4 > "$HOME/.config/emagnet/tmp/.2"
+        grep  -v -x -F -f "$HOME/.config/emagnet/tmp/.1" "$HOME/.config/emagnet/tmp/.2" |awk -F, '!seen[$1]++'|sed "s/^/https:\/\/pastebin.com\/raw\//g" > "$HOME/.config/emagnet/tmp/.emagnet"
+    else
+        $CURL -H "$USERAGENT" -Ls "$PASTEBIN/archive" \
+        |awk -F'href="/' '{print $2}' \
+        |cut -d'"' -f1 \
+        |awk 'length($0)>6 && length($0)<9' \
+        |grep -v 'archive\|contact\|settings\|messages\|signup\|index.html' \
+        |awk '{print tolower($0)}' > $HOME/.config/emagnet/tmp/.emagnet1
+        ls -1 "$EMAGNETALL" \
+        |sort > "$HOME/.config/emagnet/tmp/.1"
+        cat "$HOME/.config/emagnet/tmp/.emagnet1" \
+        |sort \
+        |cut -d/ -f5 > "$HOME/.config/emagnet/tmp/.2"
+        grep  -v -x -F -f "$HOME/.config/emagnet/tmp/.1" "$HOME/.config/emagnet/tmp/.2" |awk -F, '!seen[$1]++'|sed "s/^/https:\/\/pastebin.com\/raw\//g" > "$HOME/.config/emagnet/tmp/.emagnet"
+      fi
+      rm "$HOME/.config/emagnet/tmp/.1" "$HOME/.config/emagnet/tmp/.2" &> /dev/null
       if [[ "$(cat $HOME/.config/emagnet/tmp/.emagnet1|wc -l)"      = "8" ]];  then emagnet_notice_about_scraping         ;fi
-      if [[ "$(cat $HOME/.config/emagnet/tmp/.emagnet1|grep https)" = "0" ]];  then emagnet_heavyload;emagnet_I_was_banned;fi
-       xargs -P "${THREADS}" -n 1 wget --user-agent="${USERAGENT}" -q -nc -P "$EMAGNETTEMP" < $HOME/.config/emagnet/tmp/.emagnet &> /dev/null
-       tt="$(cat $HOME/.config/emagnet/tmp/.emagnet| wc -l)";[[ "$tt" -lt "10" ]] && tt="0$tt"
+      if [[ "$(cat $HOME/.config/emagnet/tmp/.emagnet1|grep https|wc -l)" = "0" ]];  then emagnet_heavyload;emagnet_I_was_banned;fi
+       xargs -P "$(xargs --show-limits -s 1 2>&1|grep -i "parallelism"|awk '{print $8}')" -n 1 wget --user-agent="${USERAGENT}" -q -nc -P "$EMAGNETTEMP" < $HOME/.config/emagnet/tmp/.emagnet &> /dev/null
+      tt="$(cat $HOME/.config/emagnet/tmp/.emagnet| wc -l)"
+      [[ "$tt" -lt "10" ]] && tt="0$tt"
+      el=$(grep -rEiEio '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b' $EMAGNETTEMP|cut -d: -f2|tr ' ' '\n'|awk -F, '!seen[$1]++')
+      et=$(grep -rEiEio '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b' $EMAGNETTEMP|tr ' ' '\n'|wc -l)
+      ef=$(grep -rEiEio "\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b" $EMAGNETTEMP|grep '\S'|sed 's/|/:/g'|awk '{print $1}'|cut -d: -f1|uniq|grep -v '"'\|','\|'<'|tr ' ' '\n')
+      pf=$(grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b\\:.*$" $EMAGNETTEMP|grep '\S'|sed 's/|/:/g'|awk '{print $1}'|cut -d: -f1|uniq|grep -v '"'\|','\|'<'|tr ' ' '\n')
+      pl=$(grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b\\:.*$" "$EMAGNETTEMP"|awk '{print $1}'|cut -d':' -f2,3|cut -d'|' -f1|awk -F, '!seen[$1]++'|grep -v ''\|'/'\|'"'\|','\|'<'\|'>'\|'\/'\|'\\'\|'index.html'\|'alerts'|grep -v '/')
+      pt=$(grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b:...*" $EMAGNETTEMP|awk '{print $1}'|cut -d: -f2,3|uniq|grep -v ''\|'/'\|'"'\|','\|'<'\|'>'\|'\/'\|'\\'|grep -v /|wc -l)
+      [[ "$et" -lt 10 ]] && et="0$et";[[ "$pt" -lt 10 ]] && pt="0$pt"
+         
          if [[ "${tt}" -eq "00" ]]; then
            grep -rEiEio '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b' "$EMAGNETTEMP"|cut -d: -f1|tr ' ' '\n'
-	   printf "[\e[1;31m<<\e[0m] - No new files could be downloaded..\n[\e[1;31m<<\e[0m] - Increase time or you will get banned anytime now..\n\n"
+	         printf "[\e[1;31m<<\e[0m] - No new files could be downloaded..\n[\e[1;31m<<\e[0m] - Increase time or you will get banned anytime now..\n\n"
            tt="\e[1;31m\e[5m00\e[0m"
       	   sleep 5 # Sleep here for make some room, this will not cause any problems with missing files
            emagnet_clear;emagnet_banner
@@ -948,16 +975,9 @@ emagnet_main() {
            paste 1 2|sed 's/ago/after upload/g'|sed 's/\t//g'|sed '$d' >> "$EMAGNETLOGS/pastebin-urls.txt"
            rm "./1" "./2"
         fi
+         
+         if [[ "$pt" -gt "00" ]] && [[ "$et" -gt "00" ]]; then
 
-el=$(grep -rEiEio '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b' $EMAGNETTEMP|cut -d: -f2|tr ' ' '\n'|awk -F, '!seen[$1]++')
-et=$(grep -rEiEio '\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b' $EMAGNETTEMP|tr ' ' '\n'|wc -l)
-ef=$(grep -rEiEio "\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b" $EMAGNETTEMP|grep '\S'|sed 's/|/:/g'|awk '{print $1}'|cut -d: -f1|uniq|grep -v '"'\|','\|'<'|tr ' ' '\n')
-pf=$(grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b\\:.*$" $EMAGNETTEMP|grep '\S'|sed 's/|/:/g'|awk '{print $1}'|cut -d: -f1|uniq|grep -v '"'\|','\|'<'|tr ' ' '\n')
-pl=$(grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b\\:.*$" "$EMAGNETTEMP"|awk '{print $1}'|cut -d':' -f2,3|cut -d'|' -f1|awk -F, '!seen[$1]++'|grep -v ''\|'/'\|'"'\|','\|'<'\|'>'\|'\/'\|'\\'\|'index.html'\|'alerts'|grep -v '/')
-pt=$(grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b:...*" $EMAGNETTEMP|awk '{print $1}'|cut -d: -f2,3|uniq|grep -v ''\|'/'\|'"'\|','\|'<'\|'>'\|'\/'\|'\\'|grep -v /|wc -l)
-
-[[ "$et" -lt 10 ]] && et="0$et";[[ "$pt" -lt 10 ]] && pt="0$pt"
-          if [[ "$pt" > "00" ]] && [[ "$et" > "00" ]]; then
             echo -e "[$(date +%d/%m/%Y\ -\ %H:%M)]: Found ${pt} passwords from: $EMAGNETPW/${pf##*/}"      | xargs >> "$EMAGNETLOGS/emagnet.log"
             echo -e "[$(date +%d/%m/%Y\ -\ %H:%M)]: Found ${et} email addresses from: $EMAGNETDB/${ef##*/}"|xargs >> "$EMAGNETLOGS/emagnet.log"
             echo -e "${pl}" >> $EMAGNETLOGS/passwords-from-pastebin.txt
@@ -993,11 +1013,11 @@ pt=$(grep -rEiEio "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b:...*" $EM
                   printf "%64s \n\n" | tr ' ' '='
                   printf "%15s";printf "BRUTE FORCING -- \e[1;31mRDP\e[0m ACCOUNTS\e[0m\n\n"
                   emagnet_rdpbruter
-
                 else
                   sleep 0
                fi
                 elif [[ "$pt" = "0" ]] && [[ "$et" -gt "0" ]]; then
+                  [[ "$et" -lt 10 ]] && et="0$et";[[ "$pt" -lt 10 ]] && pt="0$pt"
                    cp -rn ${ef} $EMAGNETDB/ &> /dev/null
                    echo -e "${el}" >> "$EMAGNETLOGS/emails-from-pastebin.txt"
                    echo -e "[$(date +%d/%m/%Y\ -\ %H:%M)]: Found ${et} email addresses from $EMAGNETDB/${e##*/}"|xargs >> "$EMAGNETLOGS/emagnet.log"
@@ -1087,7 +1107,7 @@ fi
 }
 
 emagnet_search() {
-    emagnet_requirements
+	emagnet_requirements
     dt="$(date +%d%m%y)"
     emagnet_conf
     emagnet_clear
@@ -1176,10 +1196,40 @@ read -p " [O] - Option: " diagst
         esac
 }
 
+
+countdown() {
+  emagnet_clear;emagnet_banner
+  sed -i 's/API=true/API=false/g' $CONF
+  echo -e "You forgot to whitlist your IP on pastebin, changing API to false..."
+  echo -e "If this is wrong, go whitelist your ip here: https://pastebin.com/doc_scraping_api...\n"
+  echo -e "Emagnet will take latest uploads from pastebin.com/archive until you solve this..."
+
+  secs=10
+  shift
+  msg=$@
+  while [ $secs -gt 0 ]
+  do
+             printf "\r\033[KContinues in %.d seconds $msg..." $((secs--))
+    sleep 1
+  done
+  echo
+}
+
 case "${1}" in
 
      "-a"|"-author"|"--author")
           emagnet_author
+     ;;
+
+     "-A"|"-api"|"--api")
+        if [[ $2 = true ]]; then
+          sed -i 's/API=false/API=true/g' $CONF
+          echo -e "$basename$0: config updated -- API has been set to true"
+        else
+          sed -i 's/API=false/API=false/g' $CONF
+          sed -i 's/API=true/API=false/g' $CONF
+          echo -e "$basename$0: config updated -- API has been set to false"
+        fi
      ;;
 
      "-B"|"--banned"|"--blocked")
@@ -1187,14 +1237,18 @@ case "${1}" in
       ;;
 
      "emagnet"|"-e"|"-emagnet"|"--emagnet")
+	emagnet_firstrun
         emagnet_iconnection
         emagnet_first_run
-        emagnet_requirements
         sed -i 's/GBRUTEFORCE=true/GBRUTEFORCE=false/g' "$CONF"
         sed -i 's/SBRUTEFORCE=true/SBRUTEFORCE=false/g' "$CONF"
         sed -i 's/PBRUTEFORCE=true/PBRUTEFORCE=false/g' "$CONF"
         sed -i 's/IBRUTEFORCE=true/IBRUTEFORCE=false/g' "$CONF"
         sed -i 's/RBRUTEFORCE=true/RBRUTEFORCE=false/g' "$CONF"
+        curl -s https://scrape.pastebin.com/api_scraping.php|grep -qi "NOT HAVE ACCESS"
+           if [[ "$?" -eq "0" ]]; then 
+               countdown
+           fi
         emagnet_run4ever
 		  ;;
       "-S"|"-search"|"--search")
