.

diff --git a/emagnet b/emagnet
--- a/emagnet
+++ b/emagnet
@@ -1246,7 +1246,10 @@ case "${1}" in
 
            elif [[ "$2" = "spotify" ]]; then
            emagnet_conf
-             if [[ -f "/usr/include/portaudiocpp/" ]]; then echo "portaudio is required to be installed ..."; fi; exit 1  
+             if [[ ! -f "/usr/include/portaudiocpp/" ]]; then 
+                echo "portaudio is required to be installed ..."; 
+             fi
+             exit 1
              find /usr/include -type d |grep 'libspotify' &> /dev/null
              if [[ "$?" -ne "0" ]]; then
              if [[ -z "$LIBSPOTIFY" ]]; then
